"""THE PACKAGED SEED VAULT IS A SEED, NOT A SAVE FILE.

THE LIVE DEFECT (observed on this branch, P4-B2)
    A real-vault smoke of `systemu census grant` ran against the CHECKOUT'S OWN
    `systemu/vault/`.  Two runtime files were created there and then swept into
    commit 32d3f3d9 by a `git add` that did not read what it was adding:

        systemu/vault/census_consent.json               (a signed R-W2 grant file)
        systemu/vault/secrets/dashboard_session.secret  (a per-vault secret)

    Both are runtime state.  Both were TRACKED, so both would have shipped in
    the wheel.  That is two distinct failures, and neither is cosmetic:

      1. A SECRET IN GIT.  `dashboard_session.secret` is the per-vault seed
         `dashboard_auth.session_secret` mints once and persists; it keys the
         dashboard session cookie AND -- by the domain separation in
         `census_consent._consent_key` -- the census consent MAC.  A committed
         one is published to every reader of the repository and identical on
         every install, which collapses "per-vault" to "global".  The specific
         bytes here were generated by a test run on a developer machine and
         were never an operator's, but they are BURNED regardless: the rule is
         that a secret which reaches a commit is rotated, not assessed.
      2. A SIGNED CONSENT FILE SHIPPING IN THE WHEEL, keyed to that same
         shipped secret.  The R-W2 authenticator's whole claim is that forging
         a grant requires the vault's own secret.  Ship the secret alongside a
         file it signs and the claim is void: every install would start from a
         consent file whose MAC verifies against a key anyone can read.  (The
         committed file happened to carry `"grants": {}`, so it granted
         nothing -- but "the forged artifact was empty this time" is not a
         property, it is luck.)

    This is the SAME CLASS as the vault-root incident that
    `tests/test_vault_root_resolution.py` documents, reached by a different
    road.  There, a daemon resolved its OPERATING vault into the package tree
    and wrote `.systemu_daemon.json`, `.effect_tags_seed`, `.first_gate_review`,
    `.package_manifest_baseline.json`, `secrets/dashboard_session.secret`,
    `capabilities/`, `metrics/`, `table/` and `manual_events.jsonl` into the
    checkout.  That test fences the RESOLUTION.  Nothing fenced the COMMIT --
    so any future test, smoke or stray `--vault-dir systemu/vault` that drops a
    file there could be committed again, silently, by a wildcard `git add`.

PROPERTY
    `git ls-files systemu/vault/` names no runtime state: nothing under
    `secrets/`, no consent file, no lock, and none of the side-store or
    incident-dropping names enumerated in `RUNTIME_STATE_NAMES` /
    `RUNTIME_STATE_DIRS` below.  The seed keeps exactly what a fresh install
    needs to have SHIPPED -- tools/, skills/, shadow_army/, decisions/,
    scrolls/.gitkeep -- and nothing a run PRODUCES.

WITNESS
    `git add -f systemu/vault/secrets/anything` (or a consent file, or a lock),
    commit it, and a named test here goes red.  Deleting the ignore entries
    alone does NOT go red, deliberately: the tracked-file assertion is the
    fence, and .gitignore is the ergonomic backstop that keeps a developer from
    having to remember.  Both are pinned, separately.

SOURCE OF THE NAME LIST (grounded, not invented)
    * the per-store rows of `docs/CONC-MAP.md` -- every `<root>/...` side-store
      that a running systemu writes into its vault;
    * the droppings enumerated in `tests/test_vault_root_resolution.py`'s
      module docstring, i.e. what a misresolved daemon actually left behind.
    A name here means "a RUN writes this"; it does not have to have been
    committed for the fence to be worth holding.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
VAULT = "systemu/vault"


# ---------------------------------------------------------------------------
# The runtime-state vocabulary.  Every entry is a file a RUNNING systemu
# writes into its operating vault, taken from the two grounded sources named
# in the module docstring.
# ---------------------------------------------------------------------------

#: Exact basenames that must never be tracked anywhere under systemu/vault/.
RUNTIME_STATE_NAMES = frozenset({
    # --- R-W2 census (this branch's incident) -------------------------------
    "census_consent.json",
    # --- CONC-MAP side-stores ----------------------------------------------
    "funnel.json",                     # P2d first-run funnel
    "growth_snapshot.json",            # 2a growth card
    "granted_roots.json",              # filesystem grants
    "items.json",                      # attention items
    "affinity_log.json",
    "rejection_store.json",
    "tool_metrics.json",
    "command_approvals.json",
    "dep_approvals.json",
    "dashboard_auth.json",
    "user_profile.json",
    "user_facts.jsonl",
    "manual_events.jsonl",
    "supervisor_queue.json",
    "memory_consolidation_meta.json",
    # --- vault-root incident droppings -------------------------------------
    ".systemu_daemon.json",
    ".effect_tags_seed",
    ".first_gate_review",
    ".package_manifest_baseline.json",
    # --- credentials --------------------------------------------------------
    ".credentials.json",
})

#: Directories under systemu/vault/ whose entire contents are runtime state.
#: `secrets/` is the one that actually bit us; the rest are from the same two
#: sources and are fenced for the same reason.
RUNTIME_STATE_DIRS = (
    "secrets",          # dashboard_session.secret, api_token.json
    "world_model",      # facts.json, negatives.json, surveys.json
    "capabilities",     # capability_index.json, _usage.json
    "table",            # OnTheTable pins/items/tombstones
    "metrics",
    "audit",            # ask_corpus.jsonl, ask_avoidable.jsonl
    "messaging",        # resolve_audit.jsonl
    "activities",
    "executions",
    "evolutions",
    "notifications",
    "elder",
)


def _tracked_under_vault() -> list:
    """Every path git TRACKS under systemu/vault/, from git itself.

    `git ls-files` is the authority on purpose: the question is not "what is on
    this disk" (a dirty worktree is normal and fine) but "what would ship",
    which is exactly the index/HEAD content.  Reading the filesystem instead
    would be the wrong oracle -- it would go red on every developer who has
    ever run the daemon locally, and it would go GREEN on a file that was
    committed and then deleted from the worktree.
    """
    out = subprocess.run(
        ["git", "ls-files", "--", VAULT],
        cwd=str(REPO), capture_output=True, text=True,
        encoding="utf-8", errors="backslashreplace", check=True,
    ).stdout
    return [line.strip().replace("\\", "/")
            for line in out.splitlines() if line.strip()]


@pytest.fixture(scope="module")
def tracked():
    paths = _tracked_under_vault()
    # Positive control in the same fixture: a run of `git ls-files` that
    # returns nothing would make every assertion below pass vacuously (wrong
    # cwd, a detached index, git missing).  The seed vault is not empty -- it
    # ships the starter tools -- so an empty listing means the ORACLE broke,
    # not that the tree is clean.
    assert any(p.startswith(f"{VAULT}/tools/") for p in paths), (
        "git ls-files returned no seed tools under systemu/vault/ -- the "
        "oracle is broken, so nothing below would have been able to fail. "
        f"got {len(paths)} path(s)."
    )
    return paths


# --- the fence -------------------------------------------------------------

def test_no_secret_is_tracked_under_the_packaged_vault(tracked):
    """A secret in git is published to every reader and identical on every
    install.  This is the specific file that was committed on this branch."""
    offenders = [p for p in tracked if p.startswith(f"{VAULT}/secrets/")]
    assert offenders == [], (
        "SECRET(S) TRACKED IN THE PACKAGED VAULT: " + ", ".join(offenders)
        + "\nA per-vault secret that reaches a commit is BURNED -- rotate it, "
        "do not assess it. `git rm --cached` the file, delete the working "
        "copy, and find the writer: something resolved its OPERATING vault "
        "into the checkout (see tests/test_vault_root_resolution.py)."
    )


def test_no_census_consent_file_is_tracked(tracked):
    """A signed consent file in the wheel, keyed by a secret also in the wheel,
    voids the R-W2 authenticator's entire claim."""
    assert f"{VAULT}/census_consent.json" not in tracked, (
        f"{VAULT}/census_consent.json is TRACKED. It carries an HMAC keyed by "
        "this vault's session secret; shipping it means every install starts "
        "from a consent file whose MAC verifies against a published key. "
        "Whether its `grants` happen to be empty is not the property."
    )


def test_no_lock_file_is_tracked_under_the_packaged_vault(tracked):
    """Locks are per-process liveness, never shipped content."""
    offenders = [p for p in tracked
                 if p.startswith(f"{VAULT}/") and p.endswith(".lock")]
    assert offenders == [], (
        "lock file(s) tracked under the packaged vault: " + ", ".join(offenders)
    )


def test_no_runtime_side_store_is_tracked_under_the_packaged_vault(tracked):
    """The CONC-MAP side-stores and the vault-root incident droppings, by name.

    One assertion over the whole vocabulary rather than one test per name: the
    failure message has to say WHICH name and WHERE, and a caller adding a new
    side-store should add it to one list, not write a new test.
    """
    offenders = sorted(
        p for p in tracked
        if p.startswith(f"{VAULT}/") and Path(p).name in RUNTIME_STATE_NAMES
    )
    assert offenders == [], (
        "RUNTIME STATE TRACKED IN THE PACKAGED SEED VAULT:\n  "
        + "\n  ".join(offenders)
        + "\nThese are files a RUN produces, not files an install needs. "
        "`git rm --cached` them, delete the working copies, and add the name "
        "to systemu/vault/.gitignore. If the name is legitimately seed "
        "content, that is a deliberate decision -- justify it here rather "
        "than deleting the assertion."
    )


def test_no_runtime_state_directory_is_tracked_under_the_packaged_vault(tracked):
    """Directory-shaped runtime state (secrets/, world_model/, table/, ...).

    Distinct from the by-name test because these are whole subtrees: a NEW
    file appearing under `world_model/` must fail without anyone having
    remembered to add its basename to the vocabulary.
    """
    offenders = sorted(
        p for p in tracked
        for d in RUNTIME_STATE_DIRS
        if p.startswith(f"{VAULT}/{d}/")
    )
    assert offenders == [], (
        "RUNTIME STATE DIRECTORIES TRACKED IN THE PACKAGED SEED VAULT:\n  "
        + "\n  ".join(offenders)
        + "\nThe seed ships tools/, skills/, shadow_army/, decisions/ and "
        "scrolls/.gitkeep. Everything above is written by a running systemu."
    )


# --- the ergonomic backstop ------------------------------------------------

def test_the_vault_gitignore_covers_the_runtime_state_vocabulary():
    """.gitignore must already ignore what the fence above forbids.

    Separate from the fence on purpose. The tracked-file assertions are the
    PROPERTY (they hold even if every ignore entry is deleted, because an
    ignored file can still be `git add -f`ed and a tracked file is not
    un-tracked by ignoring it). This test is the ERGONOMICS: without the
    entries, `git status` shows a wall of runtime noise after any local run,
    which is precisely the condition under which a wildcard `git add` sweeps a
    secret into a commit -- the actual causal chain of the incident above.
    """
    text = (REPO / ".gitignore").read_text(encoding="utf-8")
    missing = []
    for name in sorted(RUNTIME_STATE_NAMES):
        if f"{VAULT}/{name}" not in text and f"\n{name}\n" not in text:
            missing.append(name)
    for d in RUNTIME_STATE_DIRS:
        if f"{VAULT}/{d}/" not in text:
            missing.append(f"{d}/")
    assert missing == [], (
        "systemu/vault/ runtime state not covered by .gitignore: "
        + ", ".join(missing)
        + "\nAdd them under the vault section. An uncovered name means a local "
        "run leaves it in `git status`, which is how the P4-B2 secret got "
        "committed in the first place."
    )
