"""IVault — repository interface for all Systemu persistent entities.

Every method mirrors the current Vault public API exactly so that FileVault,
SqliteVault, and PostgresVault are drop-in replacements with zero call-site
changes.  Implementations must preserve all documented behaviours including:

  • Atomic writes (no half-written state)
  • KeyError on get_* when entity is absent
  • list_* returns lightweight header dicts, not full entity objects
  • load_index() returns the same header dicts as the matching list_* method
  • Memory operations (shadow + elder) never raise for absent files/rows
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable

from systemu.core.models import (
    Activity, ActivityStatus,
    Evolution, EvolutionStatus,
    Notification,
    Scroll, ScrollStatus,
    Shadow, ShadowStatus,
    Skill,
    Tool, ToolStatus,
)


@runtime_checkable
class IVault(Protocol):
    """Backend-agnostic vault interface.  All implementations must be thread-safe."""

    # ── Index ─────────────────────────────────────────────────────────────────

    def load_index(self, entity: str) -> List[Dict[str, Any]]:
        """Return the lightweight header list for a given entity type.

        entity: "scrolls" | "activities" | "skills" | "tools" |
                "shadow_army" | "evolutions" | "notifications"
        """
        ...

    # ── Scroll ────────────────────────────────────────────────────────────────

    def save_scroll(self, scroll: Scroll) -> None: ...
    def get_scroll(self, scroll_id: str) -> Scroll: ...
    def list_scrolls(self, status: Optional[ScrollStatus] = None) -> List[Dict[str, Any]]: ...

    # ── Skill ─────────────────────────────────────────────────────────────────

    def save_skill(self, skill: Skill) -> None: ...
    def get_skill(self, skill_id: str) -> Skill: ...
    def find_skill_by_name(self, name: str) -> Optional[Skill]: ...
    def list_skills(self) -> List[Dict[str, Any]]: ...

    # ── Tool ──────────────────────────────────────────────────────────────────

    def save_tool(self, tool: Tool) -> None: ...
    def get_tool(self, tool_id: str) -> Tool: ...
    def find_tool_by_name(self, name: str) -> Optional[Tool]: ...
    def list_tools(self, status: Optional[ToolStatus] = None) -> List[Dict[str, Any]]: ...

    # ── Activity ──────────────────────────────────────────────────────────────

    def save_activity(self, activity: Activity) -> None: ...
    def get_activity(self, activity_id: str) -> Activity: ...
    def list_activities(self, status: Optional[ActivityStatus] = None) -> List[Dict[str, Any]]: ...

    # ── Shadow ────────────────────────────────────────────────────────────────

    def save_shadow(self, shadow: Shadow) -> None: ...
    def get_shadow(self, shadow_id: str) -> Shadow: ...
    def list_shadows(self, status: Optional[ShadowStatus] = None) -> List[Dict[str, Any]]: ...
    def prune_old_executions(self, max_keep: int = 50) -> int: ...

    # ── Shadow memory ─────────────────────────────────────────────────────────

    def save_shadow_memory(self, shadow_id: str, memory_md: str) -> None: ...
    def load_shadow_memory(self, shadow_id: str) -> tuple[str, List[Dict[str, Any]]]: ...
    def append_memory_buffer(self, shadow_id: str, entry: Dict[str, Any]) -> None: ...
    def clear_memory_buffer(self, shadow_id: str) -> None: ...

    # ── Memory tier gate-keepers (v0.2.2) ─────────────────────────────────────
    # These are the only sanctioned writers for new code.  They stamp
    # tier provenance and enforce the cross-tier wall.  See
    # docs/memory-model.md for the full contract.
    def append_shadow_memory_buffer(
        self, shadow_id: str, entry: Dict[str, Any], *, source: str,
    ) -> Dict[str, Any]: ...
    def append_elder_buffer(
        self, entry: Dict[str, Any], *, source: str,
    ) -> Dict[str, Any]: ...

    # ── Elder / Global memory ─────────────────────────────────────────────────

    def load_elder_memory(self) -> str: ...
    def save_elder_memory(self, md_text: str) -> None: ...
    def append_elder_memory_buffer(self, entry: Dict[str, Any]) -> None: ...
    def load_elder_memory_buffer(self) -> List[Dict[str, Any]]: ...
    def clear_elder_memory_buffer(self) -> None: ...

    # Canonical aliases used by most call sites
    def load_global_memory(self) -> str: ...
    def save_global_memory(self, md_text: str) -> None: ...
    def append_global_memory_buffer(self, entry: Dict[str, Any]) -> None: ...
    def clear_global_memory_buffer(self) -> None: ...

    # ── Chat history ──────────────────────────────────────────────────────────

    def append_chat_history(self, entry: Dict[str, Any]) -> None: ...
    def load_chat_history(self, limit: int = 50) -> List[Dict[str, Any]]: ...
    def update_chat_history_entry(self, ts: str, updates: Dict[str, Any]) -> None: ...
    def get_latest_chat_scroll(self) -> Optional[Scroll]: ...

    # ── Evolution ─────────────────────────────────────────────────────────────

    def save_evolution(self, evolution: Evolution) -> None: ...
    def get_evolution(self, evolution_id: str) -> Evolution: ...
    def list_evolutions(self, status: Optional[EvolutionStatus] = None) -> List[Dict[str, Any]]: ...

    # ── Notification ──────────────────────────────────────────────────────────

    def queue_notification(self, notification: Notification) -> None: ...
    def resolve_notification(self, notification_id: str, resolution: str) -> None: ...
    def list_pending_notifications(self) -> List[Dict[str, Any]]: ...
